language: java
jdk:
  - oraclejdk7
  - openjdk7

install:
  - mvn install -Dmaven.test.skip

script: 
  - mvn verify -Pcassandra-1.1
  - mvn verify -Pcassandra-1.2,skip-unit-tests
  - mvn verify -Pcassandra-2.0,skip-unit-tests

notifications:
  irc: "irc.freenode.net#blueflood"
  email:
    recepients:
      - blueflood-discuss@googlegroups.com
