language: java
jdk:
  - oraclejdk7
  - openjdk7

install:
  - mvn install -Dmaven.test.skip -Dmaven.javadoc.skip

script: 
  - mvn verify -Pcassandra-2.0 -Dmaven.javadoc.skip --quiet

notifications:
  irc: "irc.freenode.net#blueflood"
  email:
    recepients:
      - blueflood-discuss@googlegroups.com
