name: "Periodic automatic release"

on:
  push:
    tags:
      - '*'

jobs:
  tagged-release:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        java-version: [ 8 ]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: rohit/test-cli
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java-version }}
          cache: 'maven'
      - name: Configure Git user
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git remote -v
      - name: Set version in env
        run: |
          version="${GITHUB_REF#refs/tags/}"
          echo "RELEASE_VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
      - name: Generate changelog
        id: changelog
        uses: metcalfc/changelog-generator@v0.4.4
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and deploy
        run: |
          pwd
          git checkout -b release/${RELEASE_VERSION}
          echo "${{ steps.changelog.outputs.changelog }}" > CHANGELOG.md
          git add CHANGELOG.md
          mvn -B release:prepare -DreleaseVersion=${RELEASE_VERSION} -DpushChanges=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=60 -Darguments="-DskipTests=true"
          cd /home/runner/work/blueflood/blueflood
          git status
          git push origin release/${RELEASE_VERSION}
#          mvn -B verify --no-transfer-progress -Dmaven.wagon.httpconnectionManager.ttlSeconds=60 -DskipTests=true
#          git add -- pom.xml blueflood-core/pom.xml blueflood-elasticsearch/pom.xml blueflood-http/pom.xml blueflood-cloudfiles/pom.xml blueflood-rollupTools/pom.xml blueflood-integration-tests/pom.xml blueflood-all/pom.xml
#          git commit -m "Changing pom versions"
#          git push release/${RELEASE_VERSION}
#         cp /home/runner/work/blueflood/blueflood/blueflood-all/target/blueflood-all-*-jar-with-dependencies.jar /home/runner/work/blueflood/blueflood/blueflood-all/target/blueflood-all-${RELEASE_VERSION}-jar-with-dependencies.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#      - name: Create GitHub Release
#        id: create_release
#        uses: actions/create-release@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          tag_name: ${{ github.event.inputs.releaseversion }}
#          release_name: ${{ github.event.inputs.releaseversion }}
#          body: |
#            Grab the new version from Maven central https://repo1.maven.org/maven2/de/codecentric/cxf-spring-boot-starter/${{ github.event.inputs.releaseversion }}/ by using it in your deps (also use the newest cxf-spring-boot-starter-maven-plugin https://github.com/codecentric/cxf-spring-boot-starter-maven-plugin):
#
#            ```
#            <dependencies>
#              <dependency>
#                  <groupId>com.rackspace</groupId>
#                  <artifactId>blueflood</artifactId>
#                  <version>${{ github.event.inputs.releaseversion }}</version>
#              </dependency>
#            </dependencies>
#            ```
#
#            ### Things that changed in this release
#            ${{ steps.changelog.outputs.changelog }}
#          draft: false
#          prerelease: false
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            /home/runner/work/blueflood/blueflood/blueflood-all/target/blueflood-all-${RELEASE_VERSION}-jar-with-dependencies.jar
